version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=cez-trading-datasource,cez-trading-panel
    volumes:
      - ./cez-trading-datasource/dist:/var/lib/grafana/plugins/cez-trading-datasource
      - ./cez-trading-panel/dist:/var/lib/grafana/plugins/cez-trading-panel
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
